/**
 * Pipeline Approval API
 *
 * POST /api/pipeline/prd/[run_id]/approve
 *
 * Approves the PRD skeleton generated by Agent 2 (PRDArchitectAgent).
 * User may optionally modify the skeleton before approval.
 * Transitions the pipeline run from 'awaiting_approval' to 'approved'.
 */

import { NextRequest, NextResponse } from 'next/server';
import { auth } from '@/lib/auth';
import { getPipelineRun, updatePipelineRunStatus } from '@/lib/prd-db';
import type { PRDSkeletonSection } from '@/lib/prd-db';

/**
 * Request body type.
 */
interface ApproveRequest {
  skeleton?: PRDSkeletonSection[];
}

export async function POST(
  req: NextRequest,
  { params }: { params: Promise<{ run_id: string }> }
) {
  const session = await auth();
  if (!session?.user?.email) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const { run_id } = await params;
  const run = await getPipelineRun(run_id);

  if (!run) {
    return NextResponse.json({ error: 'Run not found' }, { status: 404 });
  }

  if (run.created_by !== session.user.email) {
    return NextResponse.json({ error: 'Forbidden' }, { status: 403 });
  }

  if (run.status !== 'awaiting_approval') {
    return NextResponse.json(
      { error: 'Run is not awaiting approval' },
      { status: 409 }
    );
  }

  let body: Partial<ApproveRequest>;
  try {
    body = await req.json();
  } catch {
    body = {};
  }

  const skeleton: PRDSkeletonSection[] = body.skeleton ?? run.skeleton_json ?? [];

  const updated = await updatePipelineRunStatus(run_id, 'approved', {
    skeleton_json: skeleton,
  });

  return NextResponse.json({
    id: updated.id,
    status: updated.status,
  });
}
